global using Cowbania.Core.Gameplay;
global using Cowbania.Core.Gameplay.Combat;
global using Cowbania.Core.Gameplay.Enemies;
global using Cowbania.Core.Gameplay.Input;
global using Cowbania.Core.Gameplay.Pickups;
global using Cowbania.Core.Gameplay.World;
global using Cowbania.Core.Presentation.Animation;
global using Cowbania.Core.Presentation.Enemies;
global using Cowbania.Core.Presentation.Pickups;
global using Cowbania.Core.Presentation.Player;
global using Cowbania.Host.Application;
global using Cowbania.Host.Audio;
global using Cowbania.Host.Diagnostics;
global using Cowbania.Host.Feedback;
global using Cowbania.Host.Input;
global using Cowbania.Host.Presentation;
global using Cowbania.Host.Presentation.Assets;
global using Cowbania.Host.Presentation.Effects;
global using Cowbania.Host.Presentation.Hud;
global using Cowbania.Host.Presentation.Rendering;
global using Cowbania.Host.Tests.Harness;
global using static Cowbania.Host.Tests.Harness.AssertEx;
global using static Cowbania.Host.Tests.Harness.AudioTestDoubles;
global using static Cowbania.Host.Tests.Harness.AssetInventory;
global using static Cowbania.Host.Tests.Harness.PngInspection;
global using static Cowbania.Host.Tests.Harness.RepositoryFiles;
global using static Cowbania.Host.Tests.Harness.SourceInspection;
